# Generated by Django 6.0.3 on 2026-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='longitude',
        ),
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, upload_to='routes/', verbose_name='Превью маршрута'),
        ),
        migrations.AddField(
            model_name='route',
            name='steps',
            field=models.TextField(default='', help_text='Нажимайте Enter после каждого этапа', verbose_name='Этапы (каждый с новой строки)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
