# Generated by Django 6.0.3 on 2026-03-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_route_latitude_remove_route_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.CharField(default='Дубна, Россия', max_length=255, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, upload_to='routes/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='route',
            name='steps',
            field=models.TextField(verbose_name='Этапы (с новой строки)'),
        ),
    ]
