# Generated by Django 6.0.3 on 2026-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news', 'Новости'), ('event', 'Афиша'), ('party', 'Мероприятие'), ('info', 'Инфо')], default='news', max_length=20, verbose_name='Категория'),
        ),
    ]
