# Generated by Django 6.0.3 on 2026-03-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='lat',
            field=models.FloatField(default=56.732, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='route',
            name='lon',
            field=models.FloatField(default=37.167, verbose_name='Долгота'),
        ),
    ]
